name: Voting App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # BƯỚC MỚI 1: Robot dùng chìa khóa bí mật để mở cửa kho Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # BƯỚC MỚI 2: Build xong là Phóng (Push) thẳng lên kho
      - name: Build and Push Vote App
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest ./vote
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

      - name: Build and Push Result App
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/result:latest ./result
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

      - name: Build and Push Worker App
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest ./worker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest